pipeline:
  build_mono:
    image: mono:3.10
    commands:
      - mcs Program.cs SimpleWebServer.cs -o ${DRONE_REPO_NAME}.exe
  build_dotnet:
    image: microsoft/dotnet 
    commands:
      - dotnet build -c Release -o out
  publish_mono:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: josmo/mono_docker
    tag:
      - latest
      - ${DRONE_BUILD_NUMBER}
    file: Dockerfile
    insecure: true
    when:
      local: false
      event: [ push ]
  publish_dotnet:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: josmo/dotnet_docker
    tag:
      - latest
      - ${DRONE_BUILD_NUMBER}
    file: Dockerfile.dotnet
    insecure: true
    when:
      local: false
      event: [ push ]
  deploy:
    image: peloton/drone-rancher
    url: http://rancher.seattleslow.com
    secrets: [ rancher_access_key, rancher_secret_key ]
    service: csharp/web
    docker_image: josmo/mono_docker:${DRONE_BUILD_NUMBER}
    start_first: false
    confirm: true
    timeout: 180
    when:
      local: false
      event: push

  deploy:
    image: peloton/drone-rancher
    url: http://rancher.seattleslow.com
    secrets: [ rancher_access_key, rancher_secret_key ]
    service: csharp/web-dotnet
    docker_image: josmo/dotnet_docker:${DRONE_BUILD_NUMBER}
    start_first: false
    confirm: true
    timeout: 180
    when:
      local: false
      event: push
